apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
#   labels:
#     app: simple-web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: web-app-nginx
        image: app:2.0
        ports:
        - containerPort: 80 #the port of the container within the pod